name: slice_job
description: A Flutter project for slice job.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_color_gen: ^2.0.0
  provider: ^6.0.2
  sliding_clipped_nav_bar: ^2.0.1+8
  ionicons: ^0.1.2
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  social_login_buttons: ^1.0.6+2
  pretty_json: ^2.0.0
  panara_dialogs: ^0.0.5
  future_progress_dialog: ^0.2.0
  pinput: ^2.1.4

  connectivity_plus: ^2.2.1
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: google_fonts/AlegreyaSans-Thin.ttf
          weight: 100
        - asset: google_fonts/AlegreyaSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/AlegreyaSans-Light.ttf
          weight: 300
        - asset: google_fonts/AlegreyaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/AlegreyaSans-Regular.ttf
          weight: 400
        - asset: google_fonts/AlegreyaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/AlegreyaSans-Medium.ttf
          weight: 500
        - asset: google_fonts/AlegreyaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: google_fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: google_fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic